from src.internal.tree import *

t = NavigateTree()

t.insertFolderNode([''], {'name': 'test', 'id': 'testid1'})
t.insertFolderNode([''], {'name': 'testtwo', 'id': 'testid2'})
t.insertFolderNode([''], {'name': 'testfive', 'id': 'testid3'})
t.insertFileNode(['testfive'], {'name': 'fileinfive', 'id': 'testfivefile'})
t.insertFileNode(['test'], {'name': 'test2', 'id': 'testid4'})
t.insertFolderNode(['test'], {'name': 'test2folder', 'id': 'testid5'})
t.insertFolderNode(['test', 'test2folder'], {'name': 'testeststset', 'id':'uuidv3'})
t.insertFolderNode(['test', 'test2folder', 'testeststset'], {'name': 'testINnnasfdasfer', 'id':'inner'})
t.insertFolderNode(['test', 'test2folder', 'testeststset', 'testINnnasfdasfer'], {'name': 'testINnnasfdaasfsfer1111', 'id':'inner'})
t.insertFileNode(['test', 'test2folder', 'testeststset'], {'name': 'testINnner', 'id':'inner'})
t.insertFileNode(['test', 'test2folder', 'testeststset'], {'name': 'testINnner123123', 'id':'inner'})
tem = t.traverse(['test'])
# print(tem.children.keys())
tem = t.traverse(['test', 'test2folder'])
# print(tem.children.keys())
t.deleteFolderNode(['test', 'test2folder'], 'testeststset')
# print(tem.children.keys())
printNavigateTreeByDepth(t)

print(treeToJSON(t.root))
print(t.itemsCount)
# print(breathFirstSearch(tem, 2))
# print(childrenToJSON(t.root))
